// packages/app-react/src/views/InnUI/index.tsx
import { useNamespace } from '@innbell/utils';
import { InnCalculator } from '@/components/innbell-ui';
import { InnButton } from '@/components/innbell-ui';
import './index.scss'

const InnUI = () => {
  const ns = useNamespace('InnUI');
  const btnNs = useNamespace('InnUI-btn');

  return (
    <div className={ns.b()}>
      <div className={ns.e('title')}>This is a React demo that uses the Innbell-ui Button.</div>
      <div className={btnNs.b()}>
        <div className={btnNs.e('group')}>
          <div className={btnNs.e('title')}>base</div>
          <InnButton>default</InnButton>
          <InnButton type="primary">primary</InnButton>
          <InnButton type="success">success</InnButton>
          <InnButton type="warning">warning</InnButton>
          <InnButton type="danger">danger</InnButton>
          <InnButton type="dashed">dashed</InnButton>
          <InnButton type="text">text</InnButton>
          <InnButton type="link">link</InnButton>
        </div>
        <div className={btnNs.e('group')}>
          <div className={btnNs.e('title')}>ghost</div>
          <InnButton ghost>default</InnButton>
          <InnButton type="primary" ghost>primary</InnButton>
          <InnButton type="success" ghost>success</InnButton>
          <InnButton type="warning" ghost>warning</InnButton>
          <InnButton type="danger" ghost>danger</InnButton>
        </div>

        <div className={btnNs.e('group')}>
          <div className={btnNs.e('title')}>ghost</div>
          <InnButton round>default</InnButton>
          <InnButton type="primary" round>primary</InnButton>
          <InnButton type="success" round>success</InnButton>
          <InnButton type="warning" round>warning</InnButton>
          <InnButton type="danger" round>danger</InnButton>
        </div>

        <div className={btnNs.e('group')}>
          <div className={btnNs.e('title')}>ghost + round</div>
          <InnButton ghost round>default</InnButton>
          <InnButton type="primary" ghost round>primary</InnButton>
          <InnButton type="success" ghost round>success</InnButton>
          <InnButton type="warning" ghost round>warning</InnButton>
          <InnButton type="danger" ghost round>danger</InnButton>
        </div>

        <div className={btnNs.e('group')}>
          <div className={btnNs.e('title')}>circle</div>
          <InnButton circle>B</InnButton>
          <InnButton type="primary" circle>P</InnButton>
          <InnButton type="success" circle>S</InnButton>
          <InnButton type="warning" circle>W</InnButton>
          <InnButton type="danger" circle>D</InnButton>
        </div>
      </div>

      <div className={ns.e('title')}>Calculator</div>
      <InnCalculator />
    </div>
  );
};

export default InnUI;

// packages/app-vue/src/views/InnUI/index.vue
<template>
  <div :class="[ns.b()]">
    <div :class="ns.e('title')">This is a Vue demo that uses the Innbell-ui Button.</div>
    <div :class="[btnNs.b()]">
      <div :class="[btnNs.e('group')]">
        <div :class="btnNs.e('title')">base</div>
        <inn-button>default</inn-button>
        <inn-button type="primary">primary</inn-button>
        <inn-button type="success">success</inn-button>
        <inn-button type="warning">warning</inn-button>
        <inn-button type="danger">danger</inn-button>
        <inn-button type="dashed">dashed</inn-button>
        <inn-button type="text">text</inn-button>
        <inn-button type="link">link</inn-button>
      </div>
      <div :class="[btnNs.e('group')]">
        <div :class="btnNs.e('title')">ghost</div>
        <inn-button ghost>default</inn-button>
        <inn-button type="primary" ghost>primary</inn-button>
        <inn-button type="success" ghost>success</inn-button>
        <inn-button type="warning" ghost>warning</inn-button>
        <inn-button type="danger" ghost>danger</inn-button>
      </div>

      <div :class="[btnNs.e('group')]">
        <div :class="btnNs.e('title')">ghost</div>
        <inn-button round>default</inn-button>
        <inn-button type="primary" round>primary</inn-button>
        <inn-button type="success" round>success</inn-button>
        <inn-button type="warning" round>warning</inn-button>
        <inn-button type="danger" round>danger</inn-button>
      </div>

      <div :class="[btnNs.e('group')]">
        <div :class="btnNs.e('title')">ghost + round</div>
        <inn-button ghost round>default</inn-button>
        <inn-button type="primary" ghost round>primary</inn-button>
        <inn-button type="success" ghost round>success</inn-button>
        <inn-button type="warning" ghost round>warning</inn-button>
        <inn-button type="danger" ghost round>danger</inn-button>
      </div>

      <div :class="[btnNs.e('group')]">
        <div :class="btnNs.e('title')">circle</div>
        <inn-button circle>B</inn-button>
        <inn-button type="primary" circle>P</inn-button>
        <inn-button type="success" circle>S</inn-button>
        <inn-button type="warning" circle>W</inn-button>
        <inn-button type="danger" circle>D</inn-button>
      </div>
    </div>

    <div :class="ns.e('title')">Calculator</div>
    <inn-calculator></inn-calculator>
  </div>
</template>
<script lang="ts">
export default {
  name: 'InnUI',
}
</script>

<script lang="ts" setup>
import { useNamespace } from '@innbell/utils'
import { InnCalculator } from '@/components/innbell-ui'

const ns = useNamespace('InnUI')
const btnNs = useNamespace('InnUI-btn')

</script>

<style lang="scss">
@include b('InnUI'){

  @include e('title'){
    padding: $padding-s 0;
    font-size: $font-size-large;
    color: $color-primary;
    font-weight: $font-weight-bold;
  }

}

@include b('InnUI-btn'){

  .inn-button{
    margin-right: $margin-s;
  }

  @include e('group'){
    margin-bottom: $margin-m;
  }

  @include e('title'){
    padding: $padding-s 0;
    font-weight: $font-weight-bold;
  }
}
</style>
